[package]
name = "rndtable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.5"
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "1.0.62"
toml = "0.8.14"
